### ISSUE TITLE
[10] [DB] CRUD category

### ISSUE THREAD

**Issue by solatin** [ttnhan18062000/PTUDW_final_project_newspaper#10]
- Lấy tất cả
- Lấy theo id
- Thêm 
- Cập nhật
- Xóa

**Comment by ttnhan18062000** [comment]
Completed CRUD Category:
- Lấy tất cả - GTT_Category(); - [ID, Name, ParentCategoryID, ParentName]
- Lấy theo id - GTR_Category_By_ID(ID); - [ID, Name, ParentCategoryID, ParentName]
- Thêm - INS_Category(ParentCategoryID, Name); -> [result: 0 if failed, 1 if successful] 
- Cập nhật  - UPD_Category(ID, ParentCategoryID, Name); -> [result: 0 if failed, 1 if successful] 
- Xóa - DEL_Category(); -> []
Note: Passing a string type parameter to store procedures in models requires a pair of apostrophes (') around it.
Example: 
- const query = "Call INS_Category(${ParentCategoryID}, '${Name}')";
- const result = await db.raw(query);

**Comment by solatin** [comment]
Thêm hàm findByName

**Comment by ttnhan18062000** [comment]
Added GTR_Category_By_Name(Name) -> [ID, Name, ParentID, ParentName] if exists, return nothing if not exists.

**Comment by ttnhan18062000** [comment]
Data Field Limit: 
-Name: 50 chars
