### ISSUE TITLE
[11] [DB] CRUD post

### ISSUE THREAD

**Issue by solatin** [ttnhan18062000/PTUDW_final_project_newspaper#13]

**Comment by ttnhan18062000** [comment]
GTT_TopWeek_PostInfo_By_ViewCount() - Top 4 highest viewcount Post in week
GTT_Top10_PostInfo_By_ViewCount() - Top 10 higest viewcount Post
GTT_Top10_PostInfo_By_Date() - Top 10 lastest Post 
GTT_Top10_Cat_PostInfo_With_LastestPost() - Top 10 higest viewcount Category with one lastest Post each.
GTT_Top10_PostInfo_PerCat() - Top 4 higest viewcount Category with 10 lastest Post each.
-> return [ID, CategoryName, Title, PublishDate, Abstract]

GTT_Search_PostInfo(inputString, page) - Perform full-text search on Title, Abstract & Content with pagging
GTT_Search_PostInfo_NumPage(inputString) - Get number of page on full-text search
GTR_Search_PostInfo_Total(inputString) - Get number of post when search

GTT_PostInfo_Publish_Pagging(page) -> get all pagging PostInfo published in descending.
GTT_PostInfo_Publish_Pagging_By_CategoryID(CategoryID, page) -> get all pagging PostInfo published by category id in descending.
-> return 5 post [CategoryName, PostID, PublishDate, Title, Abstract]

GTR_PostDetail_By_ID(PostID) - Get post detail by post id.
-> return [Writer(Alias), CategoryName, PostID, Premium, PublishDate, Title, Abstract, Content,...]

GTT_PostTag_By_PostID(PostID) - Get all tags of post by post id.
-> return [TagID, TagName] (n rows)

GTT_PostInfo_Publish_Same_Category_By_PostID(PostID) - Get 5 posts with the same category as given post with postid
-> return 5 post [CategoryName, PostID, PublishDate, Title, Abstract]

GTR_NumPage_PostInfo_Publish_By_CategoryID(CategoryID) - Get number of post's page with category

GTT_Top5_PostInfo_Publish_By_CategoryID(CategoryID) - Get top 5 viewcount postinfo by categoryid

GTT_PostInfo_Publish_Pagging_By_TagID(TagID, Page) - Get 5 pagging PostInfo published by tag id
GTR_NumPage_PostInfo_Publish_By_TagID(TagID) - Get number of post's page with tag id
GTT_Top5_PostInfo_Publish_By_TagID(TagID) - Get top 5 viewcount postinfo by tag id

 GTT_PostDetail_By_Writer(AccountID) - Get PostDetail By Writer (as 4 post's status)

*Update 15/07/2021:
Now return records have ViewCount and TotalComment value

*Update 29/07/2021:
GTT_Top10_Cate_By_ViewCount () - Get top 10 Category by total Viewcount
GTT_Top10_Post_By_Cate (CategoryID) - Get  top 10 post by PublishDate with CategoryID
UPD_Post_ViewCount(PostID) - Update ViewCount by 1 (when user click on post)

*Update 01/08/2021:
INS_PostReport(AccountID, PostID, Date, Note) - insert new post report and set Post Status to 'Refused'.
UPD_Publish_Post_Editor(PostID, PublishDate, CategoryID) - publish post (by editor).
GTT_Draft_Post_By_Category(CategoryID) - get all Draft post detail by categoryID (editor)
(*)GTT_CategoryManageDetail_By_AccountID(AccountID) - get all category detail by accountID with number of draft post each cate (editor)

*Update 07/08/2021:
GTR_Refused_PostDetail_By_ID(PostID) - Get all information of a Refused post
UPD_Post_Draft(PostID) - update post refused to draft

*Update 16/08/2021:
Fulltext search on Content only
  GTR_Search_PostInfo_Total_Content(inputString)
  GTT_Search_PostInfo_NumPage_Content(inputString)
  GTT_Search_PostInfo_Content(inputString, page)
Fulltext search on Title/Abstract only
  GTR_Search_PostInfo_Total_Title(inputString)
  GTT_Search_PostInfo_Numpage_Title(inputString)
  GTT_Search_PostInfo_Title(inputString, page)

GTR_Total_PostInfo_Publish_By_TagID(TagID) - Get Total Post by TagID
GTR_Total_PostInfo_Publish_By_CategoryID(CategoryID) - Get To tal Post By CategoryID

**Comment by ttnhan18062000** [comment]
GTT_PostInfo_Draft() - Get all Draft post
UPD_Post_Publish(PostID, PublishDate) - Change the status of a post from Draft to Publish, set PublishDate in PostInfo.

**Comment by ttnhan18062000** [comment]
GTT_PostInfo() - Get all post
GTT_PostDetail() - get all post with detail
-> Return [PostID, CategoryName, PublishDate, Title, Abstract, PIScore(full-text search Score), PDScore(full-text search Score)] 
DEL_Cascade_Post(PostID) - Delete Post and all relevant information.
UPD_Post_Publish(PostID, PublishDate) - Change the status of a post from Draft to Publish, set PublishDate in PostInfo.
UPD_Post(PostID, WriterID, CategoryID, Premium, Title, Abstract, Content) - Change info of a post
*New: UPD_Post_PublishDate (PostID, PublishDate) - Change PublishDate

INS_PostDetail(WriterID, CategoryID, Premium(0/1), Status(Publish/Draft/Refused), PublishDate, Title, Abstract, Content) - insert new post
INS_PostTag(PostID, TagID) - insert new tag for post
DEL_PostTag(PostID, TagID) - delete a existed tag in post

**Comment by ttnhan18062000** [comment]
GTT_PostInfo() - Get all post
->Return [Writer(Alias), CategoryName, PostID, Premium, Title, Abstract]

**Comment by ttnhan18062000** [comment]
Data Field Limit:
-Title: 200 chars
-Abstract: 1000 chars
-Content: 65535 chars
