### ISSUE TITLE
[2] Layout trang chủ, trang chi tiết bài viết

### ISSUE THREAD

**Issue by solatin** [ttnhan18062000/PTUDW_final_project_newspaper#2]

**Comment by bobyba2000** [comment]
![image](https://user-images.githubusercontent.com/62866371/122636796-537ab080-d115-11eb-96da-07e099158788.png)
homepage chính

**Comment by bobyba2000** [comment]
![image](https://user-images.githubusercontent.com/62866371/122636821-6ee5bb80-d115-11eb-8aeb-5f9ac9899bb0.png)
thanh menu

**Comment by bobyba2000** [comment]
![image](https://user-images.githubusercontent.com/62866371/122636832-7907ba00-d115-11eb-97ae-ea221f868968.png)
trang đăng nhập

**Comment by bobyba2000** [comment]
![image](https://user-images.githubusercontent.com/62866371/122638503-9ab96f00-d11e-11eb-8723-5922542d3b70.png)
chi tiết bài viết
