### ISSUE TITLE
[21] [DB] CRUD tag

### ISSUE THREAD

**Issue by solatin** [ttnhan18062000/PTUDW_final_project_newspaper#25]

**Comment by ttnhan18062000** [comment]
GTT_Tag() - Get all tags
GTR_Tag_By_ID(ID) - Get tag by ID
GTR_Tag_By_Name(Name) - Get tag by Name
INS_Tag(Name) - insert/add new tag
UPD_Tag_By_ID(ID, Name) - update name of a tag by ID
DEL_Tag_By_ID(ID) - delete tag by ID

**Comment by ttnhan18062000** [comment]
Data Field Limit:
- Name: 50 chars
