### ISSUE TITLE
[22] [DB] CRUD account

### ISSUE THREAD

**Issue by solatin** [ttnhan18062000/PTUDW_final_project_newspaper#26]

**Comment by ttnhan18062000** [comment]
GTR_Account_By_Email()- get account info by email (for checking email exists in database)
UPD_INS_AccountDetail_By_ID(AccountID, FirstName, LastName, Email, DOB) - insert a new account info, update if exists

**Comment by ttnhan18062000** [comment]
GTT_Detail_Account() - get all account detail
GTR_Detail_Account_By_ID() - get account detail by id
GTR_Detail_Writer_Account_By_ID() - get writer detail by id -> return all information for writer
GTR_Detail_Editor_Account_By_ID() - get editor detail by id -> return all writer managed by editor

**Comment by ttnhan18062000** [comment]
GTT_Detail_Account() - get all account detail
GTT_Detail_Account_Writer() - get all writer detail
GTR_Detail_Account_By_ID(AccountID) - get account detail by id

GTR_Detail_Writer_Account_By_AccountID(AccountID) - get all writer info by account id
GTR_Detail_Editor_Account_By_AccountID(AccountID) - get editor detail by account id -> return all category[EditorID, CategoryID, CategoryName, ParentCategoryID, ParentCategoryName] managed by editor

INS_Detail_Account(Password, DisplayName, Email, AccountType, FirstName, LastName, DOB) - create new account with detail
UPD_AccountDetail_By_ID(AccountID, DisplayName, Email, AccountType, FirstName, LastName, DOB) - update account detail

Update specific information for each account type:
- UPD_INS_Detail_Writer_Account(AccountID, Alias) - update alias of writer (auto insert if there are not)
- INS_Detail_Editor_Account(EditorID, CategoryID) - add a category to list management of editor
- DEL_Detail_Editor_Account(EditorID, CategoryID) - remove a category from list management of editor

INS_Account_Admin_By_Admin(email, password)
INS_Account_Subscriber_By_Admin(email, password)
INS_Account_Writer_By_Admin(email, password)
INS_Account_Editor_By_Admin(email, password)
 -> Insert new account with mail, password

DEL_Account_Editor(AccountID) - delete editor with accountid
DEL_Account_Writer(AccountID) - delete writer with accountid
DEL_Account_Subscriber(AccountID) - delete subscriber with accounted

GTR_Otp_Account_Subcriber(AccountID) - Get Otp by AccountID
GTR_Status_Account_Subcriber(AccountID) - Get Status by AccointID
UDP_Status_Account_Subcriber(AccountID) - Update Status of Account to 'active' by AccountID

INS_PremiumRequest(AccountID) - Request Premium with accounted
GTT_PremiumRequest() - Get all request (RequestStatus = 0)
UPD_PremiumRequest(AccountID, ExpiredDate) - Give premium for an account

**Comment by ttnhan18062000** [comment]
Data Field Limit:
- DisplayName: 50 chars
- Email: 50 chars
- AccountType: 15 chars: "Subscriber", "Writer", "Editor", "Adminstrator"
- FirstName: 50 chars
- LastName: 50 chars
- Alias (Writer): 50 chars
