### ISSUE TITLE
[31] [Admin] Dashboard

### ISSUE THREAD

**Issue by solatin** [ttnhan18062000/PTUDW_final_project_newspaper#41]

**Comment by solatin** [comment]
Đặt mấy con hàng:
- Tổng post, category, tag, account, premium request
- Tổng view, tổng cmt, tổng subcriber, tổng premium subscribers
Không cần check điều kiện gắt gao quá nha, kiểu này hiển thị gọi là v thôi

**Comment by ttnhan18062000** [comment]
Post: GTR_Total_Post
Tag: GTR_Total_Tag
Category: GTR_Total_Category
Account: GTR_Total_Account
PremiumRequest: GTR_Total_PremiumRequest
View: GTR_Total_View
Comment: GTR_Total_Comment
Subscriber: GTR_Total_Subscriber
Premium Subscriber: GTR_Total_PremiumSubscriber
